"""replace photo_locations with photos and photo_groups

Revision ID: 0654e151234e
Revises: 58ccb515096f
Create Date: 2026-07-14 20:12:28.564756

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0654e151234e"
down_revision: str | None = "58ccb515096f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "photo_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("anchor_lat", sa.Float(), nullable=False),
        sa.Column("anchor_lng", sa.Float(), nullable=False),
        sa.Column("radius_m", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_photo_groups_user_id"), "photo_groups", ["user_id"], unique=False)
    op.create_table(
        "photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("s3_key", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("taken_at", sa.DateTime(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["group_id"], ["photo_groups.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("s3_key"),
    )
    op.create_index(op.f("ix_photos_group_id"), "photos", ["group_id"], unique=False)
    op.create_index(op.f("ix_photos_user_id"), "photos", ["user_id"], unique=False)
    op.drop_index("ix_photo_locations_user_id", table_name="photo_locations")
    op.drop_table("photo_locations")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "photo_locations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("filename", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "latitude", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False
        ),
        sa.Column(
            "longitude", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False
        ),
        sa.Column("taken_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="photo_locations_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="photo_locations_pkey"),
    )
    op.create_index("ix_photo_locations_user_id", "photo_locations", ["user_id"], unique=False)
    op.drop_index(op.f("ix_photos_user_id"), table_name="photos")
    op.drop_index(op.f("ix_photos_group_id"), table_name="photos")
    op.drop_table("photos")
    op.drop_index(op.f("ix_photo_groups_user_id"), table_name="photo_groups")
    op.drop_table("photo_groups")
    # ### end Alembic commands ###
