"""drop users.kakao_id

Revision ID: 60d56ee79361
Revises: 098b2130dbc7
Create Date: 2026-07-23 15:24:03.386604

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60d56ee79361"
down_revision: str | None = "098b2130dbc7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_kakao_id_key", "users", type_="unique")
    op.drop_column("users", "kakao_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("kakao_id", sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_unique_constraint("users_kakao_id_key", "users", ["kakao_id"])
    # ### end Alembic commands ###
